---
- name: Automate SNOW 
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
    
  vars:
    demo_username: "{{ lookup('env', 'SN_USERNAME') }}"
    problem_list: []

  tasks:

  - name: find user created problems
    servicenow.itsm.problem_info:
      query:
        - sys_created_by: LIKE {{ demo_username }}
          active: = true
    register: problems

  - name: query problem number and creation time 
    set_fact:
      problem_list: '{{ problem_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
    loop: "{{ problems.records }}"
    when: problems

  - name: Assign problem for assessment
    servicenow.itsm.problem:
      number: "{{ item.number }}"
      state: 3
      assigned_to: "{{ demo_username }}"
    loop: "{{ problem_list }}"

  - name: Create change request for resolving a problem
    servicenow.itsm.change_request:
      state: assess              # or "assess" depending on workflow
      type: standard
      category: software
      priority: moderate
      risk: low

      short_description: "Reboot the webserver"
      description: "Change required to remediate the related problem by rebooting the affected webserver."

      requested_by: "{{ demo_username }}"

      other:
        problem: "{{ item.number }}"   # Problem-Change linkage
        justification: "Reference to related problem {{ item.number }}"
        implementation_plan: "Reboot affected servers"
        backout_plan: "Restart services if reboot fails"
        test_plan: "Verify website is reachable after reboot"
        risk_impact_analysis: "Low impact change"
        start_date: "2026-02-07 02:00:00"
        end_date: "2026-02-07 02:30:00"

    loop: "{{ problem_list }}"
    register: change


    # - debug:
    #     msg: "A new change request has been created {{ change.record.number }}"