---
- name: get node facts for SNOW
  hosts: nodes
  gather_facts: true
  vars:
    node_info: []

  tasks:
    - name: Collect inventory facts
      ansible.builtin.set_stats:
        data:
          node_info: >-
            {{
              node_info + [
                {
                  'hostname': ansible_facts['hostname'],
                  'default_ip': ansible_facts['default_ipv4']['address'],
                  'default_mac': ansible_facts['default_ipv4']['macaddress'],
                  'vendor': ansible_facts['product_name'],
                  'cpu': ansible_facts['processor_vcpus'],
                  'memory_mb': ansible_facts['memtotal_mb'],
                  'os': ansible_facts['distribution'],
                  'os_version': ansible_facts['distribution_version'],
                  'architecture': ansible_facts['architecture']
                }
              ]
            }}
